"""Добавлены captain_id и vice_captain_id в squads

Revision ID: 0b87a3ae61a5
Revises: 75882eb987f6
Create Date: 2026-01-10 15:18:23.453718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b87a3ae61a5'
down_revision: Union[str, Sequence[str], None] = '75882eb987f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad_tours', sa.Column('captain_id', sa.Integer(), nullable=True))
    op.add_column('squad_tours', sa.Column('vice_captain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'squad_tours', 'players', ['vice_captain_id'], ['id'])
    op.create_foreign_key(None, 'squad_tours', 'players', ['captain_id'], ['id'])
    op.add_column('squads', sa.Column('captain_id', sa.Integer(), nullable=True))
    op.add_column('squads', sa.Column('vice_captain_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('unique_squad_per_league_per_user'), 'squads', type_='unique')
    op.create_foreign_key(None, 'squads', 'players', ['captain_id'], ['id'])
    op.create_foreign_key(None, 'squads', 'players', ['vice_captain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.create_unique_constraint(op.f('unique_squad_per_league_per_user'), 'squads', ['user_id', 'league_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('squads', 'vice_captain_id')
    op.drop_column('squads', 'captain_id')
    op.drop_constraint(None, 'squad_tours', type_='foreignkey')
    op.drop_constraint(None, 'squad_tours', type_='foreignkey')
    op.drop_column('squad_tours', 'vice_captain_id')
    op.drop_column('squad_tours', 'captain_id')
    # ### end Alembic commands ###
