"""4

Revision ID: 1718e3452c64
Revises: a993dd5c9439
Create Date: 2025-11-03 21:36:46.674040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1718e3452c64'
down_revision: Union[str, Sequence[str], None] = 'a993dd5c9439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_stats', sa.Column('substitutes_in', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('substitutes_out', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('substitutes_bench', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_stats', 'substitutes_bench')
    op.drop_column('player_match_stats', 'substitutes_out')
    op.drop_column('player_match_stats', 'substitutes_in')
    # ### end Alembic commands ###
