"""5

Revision ID: 3918540564d1
Revises: 1718e3452c64
Create Date: 2025-11-06 20:50:57.129473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3918540564d1'
down_revision: Union[str, Sequence[str], None] = '1718e3452c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_stats', sa.Column('points', sa.Integer(), nullable=True))
    op.drop_column('player_match_stats', 'dribbles_attempts')
    op.drop_column('player_match_stats', 'duels_total')
    op.drop_column('player_match_stats', 'dribbles_success')
    op.drop_column('player_match_stats', 'tackles_total')
    op.drop_column('player_match_stats', 'tackles_blocks')
    op.drop_column('player_match_stats', 'fouls_drawn')
    op.drop_column('player_match_stats', 'fouls_committed')
    op.drop_column('player_match_stats', 'passes_total')
    op.drop_column('player_match_stats', 'penalty_won')
    op.drop_column('player_match_stats', 'substitutes_out')
    op.drop_column('player_match_stats', 'tackles_interceptions')
    op.drop_column('player_match_stats', 'passes_key')
    op.drop_column('player_match_stats', 'substitutes_bench')
    op.drop_column('player_match_stats', 'substitutes_in')
    op.drop_column('player_match_stats', 'duels_won')
    op.drop_column('player_match_stats', 'penalty_committed')
    op.drop_column('player_match_stats', 'shots_total')
    op.drop_column('player_match_stats', 'passes_accuracy')
    op.drop_column('player_match_stats', 'shots_on')
    op.drop_column('player_match_stats', 'dribbles_past')
    op.add_column('squads', sa.Column('points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squads', 'points')
    op.add_column('player_match_stats', sa.Column('dribbles_past', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('shots_on', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('passes_accuracy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('shots_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_committed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('duels_won', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('substitutes_in', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('substitutes_bench', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('passes_key', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('tackles_interceptions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('substitutes_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_won', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('passes_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('fouls_committed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('fouls_drawn', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('tackles_blocks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('tackles_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('dribbles_success', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('duels_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_match_stats', sa.Column('dribbles_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player_match_stats', 'points')
    # ### end Alembic commands ###
