"""user_st_pos_change

Revision ID: 429e7a92b4e6
Revises: 66f06e4f568e
Create Date: 2025-09-14 11:42:42.099765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '429e7a92b4e6'
down_revision: Union[str, Sequence[str], None] = '66f06e4f568e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('sport_type_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'positions', 'sport_types', ['sport_type_id'], ['id'])
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'is_bot')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_interaction')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_interaction', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_bot', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'sport_type_id')
    # ### end Alembic commands ###
