"""custom league3

Revision ID: 45a15666afcb
Revises: 7e25c8fc1cba
Create Date: 2025-12-21 16:15:11.486731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45a15666afcb'
down_revision: Union[str, Sequence[str], None] = '7e25c8fc1cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_leagues', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('custom_leagues', sa.Column('registration_start', sa.DateTime(), nullable=True))
    op.add_column('custom_leagues', sa.Column('registration_end', sa.DateTime(), nullable=True))
    op.alter_column('custom_leagues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('custom_leagues', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_leagues', 'type',
               existing_type=postgresql.ENUM('COMMERCIAL', 'USER', 'CLUB', name='customleaguetype'),
               nullable=False)
    op.alter_column('custom_leagues', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('custom_leagues', 'invitation_only',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'custom_leagues', 'users', ['creator_id'], ['id'])
    op.create_unique_constraint('unique_squad_per_league_per_user', 'squads', ['user_id', 'league_id'])

    # Исправленное добавление столбца is_admin
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint('unique_squad_per_league_per_user', 'squads', type_='unique')
    op.drop_constraint(None, 'custom_leagues', type_='foreignkey')
    op.alter_column('custom_leagues', 'invitation_only',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('custom_leagues', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('custom_leagues', 'type',
               existing_type=postgresql.ENUM('COMMERCIAL', 'USER', 'CLUB', name='customleaguetype'),
               nullable=True)
    op.alter_column('custom_leagues', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_leagues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('custom_leagues', 'registration_end')
    op.drop_column('custom_leagues', 'registration_start')
    op.drop_column('custom_leagues', 'creator_id')
    # ### end Alembic commands ###
