"""squad boosts

Revision ID: 4cba50a274d0
Revises: 45a15666afcb
Create Date: 2025-12-21 16:15:11.486731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cba50a274d0'
down_revision: Union[str, Sequence[str], None] = '45a15666afcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицы boosts и squad_tours
    op.create_table('boosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('BENCH_BOOST', 'TRIPLE_CAPTAIN', 'TRANSFERS_PLUS', 'GOLD_TOUR', 'DOUBLE_BET', name='boosttype'), nullable=False),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('squad_tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_boost', postgresql.ENUM('BENCH_BOOST', 'TRIPLE_CAPTAIN', 'TRANSFERS_PLUS', 'GOLD_TOUR', 'DOUBLE_BET', name='boosttype'), nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Создаем ассоциативные таблицы
    op.create_table('squad_tour_bench_players',
    sa.Column('squad_tour_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['squad_tour_id'], ['squad_tours.id'], ),
    sa.PrimaryKeyConstraint('squad_tour_id', 'player_id')
    )
    op.create_table('squad_tour_players',
    sa.Column('squad_tour_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['squad_tour_id'], ['squad_tours.id'], ),
    sa.PrimaryKeyConstraint('squad_tour_id', 'player_id')
    )

    # Добавляем столбец available_boosts как nullable
    op.add_column('squads', sa.Column('available_boosts', sa.Integer(), nullable=True, server_default='5'))
    # Обновляем существующие записи
    op.execute("UPDATE squads SET available_boosts = 5 WHERE available_boosts IS NULL")
    # Делаем столбец NOT NULL
    op.alter_column('squads', 'available_boosts', nullable=False)

    # Добавляем current_tour_id
    op.add_column('squads', sa.Column('current_tour_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squads', 'current_tour_id')
    op.drop_column('squads', 'available_boosts')
    op.drop_table('squad_tour_players')
    op.drop_table('squad_tour_bench_players')
    op.drop_table('squad_tours')
    op.drop_table('boosts')
    # ### end Alembic commands ###
