"""tours num

Revision ID: 5c5ae56c7f7d
Revises: 0a0579922281
Create Date: 2025-12-20 13:10:39.390508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5ae56c7f7d'
down_revision: Union[str, Sequence[str], None] = '0a0579922281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('number', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_tour_number_per_league', 'tours', ['league_id', 'number'])
    op.drop_column('tours', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_tour_number_per_league', 'tours', type_='unique')
    op.drop_column('tours', 'number')
    # ### end Alembic commands ###
