"""fav_team

Revision ID: 674b0bf36e73
Revises: 68b25e4fadaa
Create Date: 2025-12-17 19:55:22.961959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674b0bf36e73'
down_revision: Union[str, Sequence[str], None] = '68b25e4fadaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squads', sa.Column('fav_team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'squads', 'teams', ['fav_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.drop_column('squads', 'fav_team_id')
    # ### end Alembic commands ###
