"""Add ondelete cascade to squad_tours.squad_id

Revision ID: 75882eb987f6
Revises: 0be71e2312bf
Create Date: 2026-01-08 12:34:25.819459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75882eb987f6'
down_revision: Union[str, Sequence[str], None] = '0be71e2312bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('squad_tours_squad_id_fkey'), 'squad_tours', type_='foreignkey')
    op.create_foreign_key(None, 'squad_tours', 'squads', ['squad_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'squad_tours', type_='foreignkey')
    op.create_foreign_key(op.f('squad_tours_squad_id_fkey'), 'squad_tours', 'squads', ['squad_id'], ['id'])
    # ### end Alembic commands ###
