"""custom league1

Revision ID: 7e25c8fc1cba
Revises: 16bf132f1243
Create Date: 2025-12-21 13:07:21.653417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e25c8fc1cba'
down_revision: Union[str, Sequence[str], None] = '16bf132f1243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('COMMERCIAL', 'USER', 'CLUB', name='customleaguetype'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('invitation_only', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_league_tours',
    sa.Column('custom_league_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_league_id'], ['custom_leagues.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('custom_league_id', 'tour_id')
    )
    op.create_table('custom_league_squads',
    sa.Column('custom_league_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_league_id'], ['custom_leagues.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('custom_league_id', 'squad_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_league_squads')
    op.drop_table('custom_league_tours')
    op.drop_table('custom_leagues')
    # ### end Alembic commands ###
