"""3

Revision ID: a993dd5c9439
Revises: f2003d3ae7ab
Create Date: 2025-11-03 21:14:47.631149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a993dd5c9439'
down_revision: Union[str, Sequence[str], None] = 'f2003d3ae7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_stats', sa.Column('shots_total', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('shots_on', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('passes_total', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('passes_key', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('passes_accuracy', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('tackles_total', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('tackles_blocks', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('tackles_interceptions', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('duels_total', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('duels_won', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('dribbles_attempts', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('dribbles_success', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('dribbles_past', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('fouls_drawn', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('fouls_committed', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_won', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_committed', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_scored', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_missed', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('penalty_saved', sa.Integer(), nullable=True))
    op.alter_column('players', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'market_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'market_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('player_match_stats', 'penalty_saved')
    op.drop_column('player_match_stats', 'penalty_missed')
    op.drop_column('player_match_stats', 'penalty_scored')
    op.drop_column('player_match_stats', 'penalty_committed')
    op.drop_column('player_match_stats', 'penalty_won')
    op.drop_column('player_match_stats', 'fouls_committed')
    op.drop_column('player_match_stats', 'fouls_drawn')
    op.drop_column('player_match_stats', 'dribbles_past')
    op.drop_column('player_match_stats', 'dribbles_success')
    op.drop_column('player_match_stats', 'dribbles_attempts')
    op.drop_column('player_match_stats', 'duels_won')
    op.drop_column('player_match_stats', 'duels_total')
    op.drop_column('player_match_stats', 'tackles_interceptions')
    op.drop_column('player_match_stats', 'tackles_blocks')
    op.drop_column('player_match_stats', 'tackles_total')
    op.drop_column('player_match_stats', 'passes_accuracy')
    op.drop_column('player_match_stats', 'passes_key')
    op.drop_column('player_match_stats', 'passes_total')
    op.drop_column('player_match_stats', 'shots_on')
    op.drop_column('player_match_stats', 'shots_total')
    # ### end Alembic commands ###
