"""player match stats

Revision ID: aea992427f1c
Revises: 5c5ae56c7f7d
Create Date: 2025-12-20 19:03:44.578133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea992427f1c'
down_revision: Union[str, Sequence[str], None] = '5c5ae56c7f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('goals_total', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appearances', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lineups', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minutes_played', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goals_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_scored', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_missed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_saved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('player_stats_league_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('player_stats_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('player_stats_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('player_stats_pkey'))
    )
    op.drop_table('player_match_stats')
    # ### end Alembic commands ###
