"""player stats 2

Revision ID: b16be0b690ad
Revises: ba7df7c5c3a4
Create Date: 2025-10-31 20:30:04.663819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16be0b690ad'
down_revision: Union[str, Sequence[str], None] = 'ba7df7c5c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'appearances',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_stats', 'lineups',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_stats', 'minutes_played',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_stats', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player_stats', 'goals_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_stats', 'yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_stats', 'yellow_red_cards',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_stats', 'red_cards',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'red_cards',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'yellow_red_cards',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'goals_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player_stats', 'minutes_played',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'lineups',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'appearances',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
