"""player stats 1

Revision ID: ba7df7c5c3a4
Revises: d98cc7750a2a
Create Date: 2025-10-31 00:04:34.692781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7df7c5c3a4'
down_revision: Union[str, Sequence[str], None] = 'd98cc7750a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'assists',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'assists',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
