"""player stats

Revision ID: d98cc7750a2a
Revises: fe46576a859c
Create Date: 2025-10-30 23:36:08.176096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98cc7750a2a'
down_revision: Union[str, Sequence[str], None] = 'fe46576a859c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('lineups', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('goals_total', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('yellow_red_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player_match_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_match_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('minutes_played', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_substitute', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('yellow_red_cards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals_conceded', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('penalty_saved', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('penalty_missed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('player_match_stats_league_id_fkey')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('player_match_stats_match_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('player_match_stats_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('player_match_stats_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('player_match_stats_pkey'))
    )
    op.drop_table('player_stats')
    # ### end Alembic commands ###
